
/**
 * (C) Copyright John Maddock 2012.
 * (C) Copyright Zachary Martin 2016 (port to javascript).
 * Use, modification and distribution are subject to the
 * Boost Software License:
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */
 
 module.exports = [
  {
    "dof": 4536808851374080,
    "ncp": 0.4536808729171753,
    "x": -0.48117321729660034,
    "p": 0.17493174977543524,
    "q": 0.8250682502245648
  },
  {
    "dof": 4536808851374080,
    "ncp": 0.4536808729171753,
    "x": 1.3978519439697266,
    "p": 0.8274588821376122,
    "q": 0.1725411178623878
  },
  {
    "dof": 5677385198338048,
    "ncp": 0.5677385330200195,
    "x": -0.5258305072784424,
    "p": 0.13707201688604065,
    "q": 0.8629279831139594
  },
  {
    "dof": 5677385198338048,
    "ncp": 0.5677385330200195,
    "x": 0.7083830237388611,
    "p": 0.5559246004826197,
    "q": 0.4440753995173803
  },
  {
    "dof": 19057916648620030,
    "ncp": 1.9057917594909668,
    "x": 3.1231675148010254,
    "p": 0.8882693584031001,
    "q": 0.11173064159689994
  },
  {
    "dof": 19057916648620030,
    "ncp": 1.9057917594909668,
    "x": 3.3844356536865234,
    "p": 0.9303822426214283,
    "q": 0.06961775737857163
  },
  {
    "dof": 36700173421772800,
    "ncp": 3.6700172424316406,
    "x": 4.675043106079102,
    "p": 0.8425578019432913,
    "q": 0.15744219805670867
  },
  {
    "dof": 36700173421772800,
    "ncp": 3.6700172424316406,
    "x": 5.042537689208984,
    "p": 0.9150492609181711,
    "q": 0.08495073908182892
  },
  {
    "dof": 45079461342740480,
    "ncp": 4.507946014404297,
    "x": 3.388906478881836,
    "p": 0.13156163646802618,
    "q": 0.8684383635319738
  },
  {
    "dof": 45079461342740480,
    "ncp": 4.507946014404297,
    "x": 5.9973297119140625,
    "p": 0.9318068205043593,
    "q": 0.06819317949564073
  },
  {
    "dof": 157509421545553920,
    "ncp": 15.75094223022461,
    "x": 17.145606994628906,
    "p": 0.9184415224638902,
    "q": 0.08155847753610979
  },
  {
    "dof": 157509421545553920,
    "ncp": 15.75094223022461,
    "x": 17.15754508972168,
    "p": 0.9202274076513849,
    "q": 0.07977259234861517
  },
  {
    "dof": 306140114898124800,
    "ncp": 30.614013671875,
    "x": 31.854141235351562,
    "p": 0.8925358923021368,
    "q": 0.10746410769786319
  },
  {
    "dof": 306140114898124800,
    "ncp": 30.614013671875,
    "x": 32.01709747314453,
    "p": 0.9197040745002657,
    "q": 0.08029592549973427
  },
  {
    "dof": 390730904542117900,
    "ncp": 39.073089599609375,
    "x": 38.045928955078125,
    "p": 0.15217241315852104,
    "q": 0.847827586841479
  },
  {
    "dof": 390730904542117900,
    "ncp": 39.073089599609375,
    "x": 38.23619079589844,
    "p": 0.20132472643110594,
    "q": 0.7986752735688941
  },
  {
    "dof": 1044709769224388600,
    "ncp": 104.47097778320312,
    "x": 104.86805725097656,
    "p": 0.6543455698504381,
    "q": 0.3456544301495618
  },
  {
    "dof": 1044709769224388600,
    "ncp": 104.47097778320312,
    "x": 105.14849090576172,
    "p": 0.7509597765074914,
    "q": 0.24904022349250868
  },
  {
    "dof": 1674453679643558000,
    "ncp": 167.44537353515625,
    "x": 166.869873046875,
    "p": 0.2824764302606307,
    "q": 0.7175235697393693
  },
  {
    "dof": 1674453679643558000,
    "ncp": 167.44537353515625,
    "x": 168.85714721679688,
    "p": 0.9209916949401606,
    "q": 0.07900830505983938
  },
  {
    "dof": 2809703283612975000,
    "ncp": 280.9703369140625,
    "x": 279.7629699707031,
    "p": 0.11364543011784099,
    "q": 0.886354569882159
  },
  {
    "dof": 2809703283612975000,
    "ncp": 280.9703369140625,
    "x": 282.4136657714844,
    "p": 0.9255360728128946,
    "q": 0.07446392718710539
  },
  {
    "dof": 7921767423114478000,
    "ncp": 792.1767578125,
    "x": 792.3184204101562,
    "p": 0.5563267401667034,
    "q": 0.4436732598332967
  },
  {
    "dof": 7921767423114478000,
    "ncp": 792.1767578125,
    "x": 793.5482788085938,
    "p": 0.91489369852628,
    "q": 0.08510630147371996
  },
  {
    "dof": 13091821180254420000,
    "ncp": 1309.18212890625,
    "x": 1308.01171875,
    "p": 0.12091797523015677,
    "q": 0.8790820247698432
  },
  {
    "dof": 13091821180254420000,
    "ncp": 1309.18212890625,
    "x": 1308.517578125,
    "p": 0.25316892936238244,
    "q": 0.7468310706376176
  }
];
