/**
 * (C) Copyright John Maddock 2005-2006, 2011.
 * (C) Copyright Paul A. Bristow 2006-2011.
 * (C) Copyright Zachary Martin 2016 (port to JavaScript).
 * Use, modification and distribution are subject to the
 * Boost Software License:
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */
export declare class Constants {
    static LNPI(): number;
    static LN2(): number;
    static LNSQRTTWOPI(): number;
    static SQRTTWOPI(): number;
    static EULMASC(): number;
    static SQRTPI(): number;
    static SQRT2(): number;
    static SQRT3(): number;
    static HALFPI(): number;
    static ONEDIVROOTTWO(): number;
    static ONEDIVROOTTWOPI(): number;
    static ONEDIVTWOPI(): number;
    static TWOPI(): number;
    static TWODIVPI(): number;
    static SQRTTWODIVPI(): number;
    static LOGROOT2PI(): number;
    static ONEDIVSQRTPI(): number;
}
