"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * (C) Copyright John Maddock 2006.
 * (C) Copyright Zachary Martin 2016 (port to javascript).
 * Use, modification and distribution are subject to the
 * Boost Software License:
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */
var Rational = require("../tools/rational").Rational;
var Lanczos = /** @class */ (function () {
    function Lanczos() {
    }
    Lanczos.lanczos_sum = function (z) {
        var num = [
            44012138428004.61,
            41590453358593.2,
            18013842787117.997,
            4728736263475.389,
            837910083628.4046,
            105583707273.42993,
            9701363618.494999,
            654914397.5482053,
            32238322.942133565,
            1128514.2194970914,
            26665.79378459859,
            381.8801248632927,
            2.5066282746310005,
        ];
        var denom = [
            0,
            39916800,
            120543840,
            150917976,
            105258076,
            45995730,
            13339535,
            2637558,
            357423,
            32670,
            1925,
            66,
            1
        ];
        return Rational.evaluate_rational(num, denom, z);
    };
    Lanczos.lanczos_sum_expG_scaled = function (z) {
        var num = [
            86091529.53418536,
            81354505.1785801,
            35236626.38815462,
            9249814.988024471,
            1639024.216687147,
            206530.8157641225,
            18976.701935302888,
            1281.0689099125595,
            63.06093343420235,
            2.207470909792528,
            0.052160586946135054,
            0.0007469903808915449,
            0.000004903180573459872,
        ];
        var denom = [
            0,
            39916800,
            120543840,
            150917976,
            105258076,
            45995730,
            13339535,
            2637558,
            357423,
            32670,
            1925,
            66,
            1
        ];
        return Rational.evaluate_rational(num, denom, z);
    };
    Lanczos.lanczos_sum_near_1 = function (dz) {
        var d = [
            4.832115561461657,
            -19.864415361403378,
            33.992742280744324,
            -31.41520692249766,
            17.027086600959933,
            -5.50772169508655,
            1.037811741948215,
            -0.10664046853735618,
            0.005276450526660654,
            -0.00010009356255971216,
            4.625909101385981e-7,
            -1.7353078144263895e-10,
        ];
        var result = 0;
        for (var k = 1; k <= d.length; k++) {
            result += (-d[k - 1] * dz) / (k * dz + k * k);
        }
        return result;
    };
    Lanczos.lanczos_sum_near_2 = function (dz) {
        var d = [
            26.969798196148307,
            -110.87054247093852,
            189.72588461192314,
            -175.33972029711074,
            95.03437648691552,
            -30.740602278166527,
            5.792405601630518,
            -0.5951993240669149,
            0.029449793591640176,
            -0.0005586586555377031,
            0.000002581888478270733,
            -9.68538541100664e-10,
        ];
        var result = 0;
        var z = dz + 2;
        for (var k = 1; k <= d.length; k++) {
            result += (-d[k - 1] * dz) / (z + k * z + k * k - 1);
        }
        return result;
    };
    Lanczos.g = function () { return 13.144565; };
    return Lanczos;
}());
exports.Lanczos = Lanczos;
