"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * (C) Copyright John Maddock 2006-2008.
 * (C) Copyright Zachary Martin 2016 (port to javascript).
 * Use, modification and distribution are subject to the
 * Boost Software License:
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */
var Random = require("./random").Random;
var Beta = require("./boostPorts/special_functions/beta").Beta;
var NonCentralBeta = require("./boostPorts/distributions/non_central_beta").NonCentralBeta;
var IBetaInverse = require("./boostPorts/special_functions/detail/ibeta_inverse").IBetaInverse;
var check = require("./errorHandling").check;
var FDist = /** @class */ (function () {
    function FDist() {
    }
    FDist.checkParameters = function (functionName, dof1, dof2, ncp, x, lowerTail, p, n, seed) {
        var params = {
            ncp: NaN,
            lowerTail: undefined
        };
        check(dof1, "dof1", "F distribution " + functionName, "positive_real");
        check(dof2, "dof2", "F distribution " + functionName, "positive_real");
        if (typeof ncp !== "undefined" && ncp !== null) {
            check(ncp, "ncp", "F distribution " + functionName, "nonnegative_real");
            params.ncp = ncp;
        }
        else {
            params.ncp = 0;
        }
        if (typeof x !== "undefined") {
            check(x, "x", "F distribution " + functionName, "real");
        }
        if (typeof lowerTail !== "undefined" && lowerTail !== null) {
            check(lowerTail, "lowerTail", "F distribution " + functionName, "boolean");
            params.lowerTail = lowerTail;
        }
        else {
            params.lowerTail = true;
        }
        if (typeof p !== "undefined") {
            check(p, "p", "F distribution " + functionName, "probability");
        }
        if (typeof n !== "undefined") {
            check(n, "n", "F distribution " + functionName, "nonnegative_integer");
        }
        if (typeof seed !== "undefined" && seed !== null) {
            check(seed, "seed", "F distribution " + functionName, "seed");
        }
        return params;
    };
    FDist.pdf = function (x, dof1, dof2, ncp) {
        // first error checking
        var params = FDist.checkParameters("pdf", dof1, dof2, ncp, x);
        if (x < 0) {
            return 0;
        }
        else if (x === 0) {
            if (dof1 < 2) {
                return Number.POSITIVE_INFINITY;
            }
            else if (dof1 === 2) {
                return Math.exp(-params.ncp / 2);
            }
            else {
                return 0;
            }
        }
        else if (params.ncp === 0) {
            // central case
            var v1x = dof1 * x;
            var result = void 0;
            if (v1x > dof2) {
                result = (dof2 * dof1) / ((dof2 + v1x) * (dof2 + v1x));
                result *= Beta.ibeta_derivative(dof2 / 2, dof1 / 2, dof2 / (dof2 + v1x));
            }
            else {
                result = dof2 + dof1 * x;
                result = (result * dof1 - x * dof1 * dof1) / (result * result);
                result *= Beta.ibeta_derivative(dof1 / 2, dof2 / 2, v1x / (dof2 + v1x));
            }
            return result;
        }
        else {
            // non central case
            var alpha = dof1 / 2;
            var beta = dof2 / 2;
            var y = x * alpha / beta;
            var r = NonCentralBeta.non_central_beta_pdf(alpha, beta, params.ncp, y / (1 + y), 1 / (1 + y));
            return r * (dof1 / dof2) / ((1 + y) * (1 + y));
        }
    };
    FDist.cdf = function (x, dof1, dof2, lowerTail, ncp) {
        // first error checking
        var params = FDist.checkParameters("cdf", dof1, dof2, ncp, x, lowerTail);
        if (x <= 0) {
            if (params.lowerTail) {
                return 0;
            }
            else {
                return 1;
            }
        }
        else if (x === Number.POSITIVE_INFINITY) {
            if (params.lowerTail) {
                return 1;
            }
            else {
                return 0;
            }
        }
        else if (params.ncp === 0) {
            // central case
            var v1x = dof1 * x;
            if (v1x > dof2) {
                if (params.lowerTail) {
                    return Beta.ibetac(dof2 / 2, dof1 / 2, dof2 / (dof2 + v1x));
                }
                else {
                    return Beta.ibeta(dof2 / 2, dof1 / 2, dof2 / (dof2 + v1x));
                }
            }
            else {
                if (params.lowerTail) {
                    return Beta.ibeta(dof1 / 2, dof2 / 2, v1x / (dof2 + v1x));
                }
                else {
                    return Beta.ibetac(dof1 / 2, dof2 / 2, v1x / (dof2 + v1x));
                }
            }
        }
        else {
            // non central case
            var alpha = dof1 / 2;
            var beta = dof2 / 2;
            var y = x * alpha / beta;
            var c = y / (1 + y);
            var cp = 1 / (1 + y);
            return NonCentralBeta.non_central_beta_cdf(c, cp, alpha, beta, params.ncp, !params.lowerTail);
        }
    };
    FDist.quantile = function (p, dof1, dof2, lowerTail, ncp) {
        // first error checking
        var params = FDist.checkParameters("quantile", dof1, dof2, ncp, undefined, lowerTail, p);
        if (p === 0) {
            if (params.lowerTail) {
                return 0;
            }
            else {
                return Number.POSITIVE_INFINITY;
            }
        }
        else if (p === 1) {
            if (params.lowerTail) {
                return Number.POSITIVE_INFINITY;
            }
            else {
                return 0;
            }
        }
        else if (params.ncp === 0) {
            // central case
            var iBetaInvEval = params.lowerTail ?
                IBetaInverse.ibeta_inv(dof1 / 2, dof2 / 2, p)
                :
                    IBetaInverse.ibetac_inv(dof1 / 2, dof2 / 2, p);
            var x = iBetaInvEval.result;
            var y = iBetaInvEval.py;
            return dof2 * x / (dof1 * y);
        }
        else {
            // non-central case
            var alpha = dof1 / 2;
            var beta = dof2 / 2;
            var x = NonCentralBeta.nc_beta_quantile(alpha, beta, params.ncp, p, !params.lowerTail);
            return (x / (1 - x)) * (dof2 / dof1);
        }
    };
    FDist.random = function (n, dof1, dof2, ncp, seed) {
        // first error checking
        var params = FDist.checkParameters("random", dof1, dof2, ncp, undefined, undefined, undefined, n, seed);
        return Random.numbers(n, FDist.quantile, [dof1, dof2, true, params.ncp], seed);
    };
    FDist.randomIterator = function (n, dof1, dof2, ncp, seed) {
        if (typeof n === "undefined" || n === null) {
            n = Number.POSITIVE_INFINITY;
        }
        // first error checking
        var params = FDist.checkParameters("random", dof1, dof2, ncp, undefined, undefined, undefined, n, seed);
        return Random.numberIterator(n, FDist.quantile, [dof1, dof2, true, params.ncp], seed);
    };
    return FDist;
}()); // end of class FDist
exports.FDist = FDist;
